server:
  port: 8080

spring:
  sql:
    init:
      mode: always
      continue-on-error: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/acmebankdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring:
      jpa:database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  jackson:
    default-property-inclusion: non_null